[package]
name = "slcsp-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.6"
serde = { version="1.0.126", features=["derive"] }
quickersort = "3.0.1"

[[bin]]
name = "slcsp-parser"
path = "bin/main.rs"
